name: Build packaged binaries

on: [push, pull_request, create]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x]
        arch: [amd64, arm64, arm/v7]
    steps:
    - uses: actions/checkout@v1
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1
      if: ${{ matrix.arch != 'amd64' }}
      with:
        platforms: ${{ matrix.arch }}
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Cache Electron binaries
      uses: actions/cache@v2
      env:
        cache-name: cache-electron-bins
      with:
        # cache location is described here:
        # https://github.com/electron/get#how-it-works
        path: ~/.cache/electron
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install system dependencies amd64 cross-build
      if: ${{ matrix.arch == 'amd64' }}
      run: |
        sudo apt update
        sudo apt install libc6-dev-i386 gcc-multilib g++-multilib
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install build deps
      run: npm install
    - name: run prebuild script
      run: npm run prebuild-linux
    - name: Build for x64 / ia32
      run: npm run build-linux --ignore-scripts
      if: ${{ matrix.arch == 'amd64' }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build for arm64v8
      run: npm run build-linux-armv8 --ignore-scripts
      if: ${{ matrix.arch == 'arm64' }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build for armv7
      run: npm run build-linux-armv7 --ignore-scripts
      if: ${{ matrix.arch == 'arm/v7' }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/upload-artifact@v2
      with:
        name: Linux-AppImages
        path: dist/*.AppImage
        if-no-files-found: error

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v1
    - name: Get npm cache directory
      id: npm-cache
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
    - uses: actions/cache@v2
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Cache Electron binaries
      uses: actions/cache@v2
      env:
        cache-name: cache-electron-bins
      with:
        # cache location is described here:
        # https://github.com/electron/get#how-it-works
        path: ~/AppData/Local/electron/Cache
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        npm install
    - name: npm build
      run: |
        npm run build-windows
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/upload-artifact@v2
      with:
        name: Windows-Installer
        path: dist/*.exe
        if-no-files-found: error

  build-darwin:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v1
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Cache Electron binaries
      uses: actions/cache@v2
      env:
        cache-name: cache-electron-bins
      with:
        # cache location is described here:
        # https://github.com/electron/get#how-it-works
        path: ~/Library/Caches/electron
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: set up env
      run: |
        npm install
    - name: npm build
      run: |
        npm run build-darwin
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/upload-artifact@v2
      with:
        name: MacOS-Image
        path: dist/*.dmg
        if-no-files-found: error
